# Generated by Django 3.2 on 2022-04-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220404_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_user.png', null=True, upload_to='media/'),
        ),
    ]
