# Generated by Django 3.2 on 2022-04-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created']},
        ),
    ]
