# Generated by Django 3.2 on 2022-03-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='post_image',
            new_name='topic_image',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='slug',
        ),
        migrations.AddField(
            model_name='topic',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='friendly_name'),
        ),
    ]
