# Generated by Django 3.2 on 2022-03-19 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_auto_20220319_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='title')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('user_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='user_name')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='slug')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='post_image')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='forum.topic')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created'],
            },
        ),
    ]
