# Generated by Django 3.2 on 2022-04-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_comment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
    ]
